### ISSUE TITLE
Duplicate symbol _ReadyState

### ISSUE THREAD

**Issue by kafermeister** [Lukas-Stuehrk/XMLHTTPRequest#2]
Old project I know, but just as an FYI, after integrating this library into our project, I was getting a "Duplicate symbol _ReadyState" on compile.

To resolve I needed to precede the ReadyState NS_ENUM with typedef, i.e.

NS_ENUM(NSUInteger, ReadyState) {
    XMLHttpRequestUNSENT=0,	// open()has not been called yet.
    XMLHTTPRequestOPENED,	    // send()has not been called yet.
    XMLHTTPRequestHEADERS,      // RECEIVED	send() has been called, and headers and status are available.
    XMLHTTPRequestLOADING,      // Downloading; responseText holds partial data.
    XMLHTTPRequestDONE          // The operation is complete.
};

to 

typedef NS_ENUM(NSUInteger, ReadyState) {
    XMLHttpRequestUNSENT=0,	// open()has not been called yet.
    XMLHTTPRequestOPENED,	    // send()has not been called yet.
    XMLHTTPRequestHEADERS,      // RECEIVED	send() has been called, and headers and status are available.
    XMLHTTPRequestLOADING,      // Downloading; responseText holds partial data.
    XMLHTTPRequestDONE          // The operation is complete.
};

Cheers
Peter

**Comment by Ehlster** [comment]
Old project, indeed. In fact, I remember that I released the project before everyone started to use similar approaches because of Facebook's React Native 😉 

Thanks for the heads-up. I'm glad that the project is still useful for somebody 😃 . Do you mind opening a pull request for the change so others could benefit?

**Comment by kafermeister** [comment]
Yes it and JavaScriptCore provides very flexible "scripting" functionality to our app (internal Enterprise app) so I'm glad I stumbled across it.  Being a laggard in the Enterprise space we still haven't got around to embracing React, but I guess we should look into it for our major next requirements.

Please request #3 created

Thanks

**Comment by Ehlster** [comment]
Fixed by #3 .

Thanks for the fix.
